@startuml reader-detail
actor User
participant "ブラウザ" as Browser
participant "DtailServlet" as Servlet
participant "detail.jsp" as JSP
participant "PostsDao" as Dao
participant "ConnectionManager" as ConnMgr
database "DB(MySQL)" as DB

User -> Browser : 「投稿を見る」クリック
Browser -> Servlet : HTTP GET /detail?postId=xxx
activate Servlet
Servlet -> Dao : new PostsDao()
activate Dao
Servlet -> Dao : getOne(postId)
Dao -> ConnMgr : getConnection()
activate ConnMgr
ConnMgr -> DB : DriverManager.getConnection(URL, USER, PASSWD)
activate DB
DB --> ConnMgr : Connectionオブジェクト
deactivate DB
ConnMgr --> Dao : Connection
deactivate ConnMgr
Dao -> DB : SELECT * FROM posts WHERE post_id=xxx
activate DB
DB --> Dao : 結果セット
deactivate DB
Dao --> Servlet : Post
deactivate Dao
Servlet -> JSP : forward(post)
activate JSP
JSP -> JSP : postを表示
JSP --> Browser : 投稿詳細HTMLを返す
deactivate JSP
deactivate Servlet
@enduml
